BEGIN;

INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q1', 'Which of the following is not true?', '["The tighter the security, the lower the network performance", "The security design and application has no effect on the performance", "Multi-layer security can be a bottleneck to the IT assets access", "The tighter the security, the higher the protection of the network"]', 'The security design and application has no effect on the performance', 'Security mechanisms always impact system performance because they consume resources such as CPU and memory. Therefore, saying security has no effect on performance is incorrect.', 'Computer Ethics', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q2', 'A relation R with X→WZ is in full functional dependency (2NF). Which of the following violates it?', '["WYZ are non-prime attributes and are determined by the primary attribute X", "Removing X from X→WXYZ returns the relation R to first normal form", "From X→WYZ, removing any of the WYZ does not affect the second normal form", "From X→WZ, R can possibly have duplicate values"]', 'Removing X from X→WXYZ returns the relation R to first normal form', 'Removing the determinant (X) breaks the dependency relationship. This does not correctly describe normalization and violates the concept of 2NF.', 'Database', 'hard', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q3', 'One of the following policy is used by queue data structure', '["LILO", "FILO", "LIFO", "None"]', 'D) None', 'Queue uses FIFO (First In First Out), which is not listed in the options.', 'Data Structures', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q4', 'Use case diagram in software development model demonstrate', '["Functional requirement of the system", "Functional and non-functional requirement of the system", "Performance requirement of the system", "Non-functional requirement of the system"]', 'Functional requirement of the system', 'Use case diagrams describe system interactions and functionality, which represent functional requirements.', 'Software Engineering', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q5', 'The basic computer instruction format with 16 bits, which of the following is not true?', '["Register reference type instruction contains 12 bits", "Address mode contains 1 bit", "The opcode contains 3 bits", "The opcode contains 4 bit"]', 'The opcode contains 4 bit', 'In a 16-bit instruction format, the opcode is typically 3 bits, not 4 bits.', 'Computer Architecture', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q6', 'Which of the following IP is used as a loop back service?', '["198.168.0.1", "127.0.0.1", "0.0.0.0", "255.255.255.255"]', 'B) 127.0.0.1', '127.0.0.1 is the loopback address used to refer to the local machine.', 'Networking', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q7', 'What will be the path if we use depth-first search strategy?

![Graph Diagram](/assets/question_7_graph.png)', '["Start → C → G", "Start → A → F → B → C → D → E → H → G", "Start → A → B → G", "Start → A → D → E → F → G"]', 'Start → A → D → E → F → G', 'DFS explores as deep as possible before backtracking, following a path like Start → A → D → E → F → G.', 'Algorithms', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q8', 'A micro-instruction is designed to specify none or one of three operations of one kind and up to six operations of another kind. Minimum number of bits required?', '["2 bit", "4 bit", "8 bit", "6 bit"]', 'C) 8 bit', '2 bits are needed for 3 operations and 3 bits for 6 operations, plus control bits, totaling 8 bits.', 'Computer Architecture', 'hard', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q9', 'What will be the final result in queue after the following operations?
enqueue(1), enqueue(2), dequeue(), dequeue(), dequeue(), enqueue(5), dequeue()', '["0", "5", "queue underflow", "None"]', 'C) queue underflow', 'After removing all elements, an extra dequeue operation causes underflow.', 'Data Structures', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q10', 'Which of the following is not true about software maintenance?', '["Maintenance is software testing", "Maintenance is used to change existing system", "Maintenance is used to add new requirements", "Maintenance is used to fix errors"]', 'Maintenance is software testing', 'Software maintenance involves fixing, updating, and improving systems, not testing.', 'Software Engineering', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q11', 'During normalization, which cannot hold?', '["First normal form is created by creating new relation from weak attributes", "Second normal form is created by decomposing relation for each partial key", "Boyce Codd Normal Form is created from strict third normal form", "Third normal form removes transitive dependency"]', 'First normal form is created by creating new relation from weak attributes', '1NF ensures atomic values and removes repeating groups. It is not about creating relations from weak attributes.', 'Database', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q12', 'In a wait-for graph, an edge from P1 to Pj signifies that ______', '["P1 is waiting for Pj to release a resource", "Pj is waiting for P1 to leave the system", "P1 is waiting for Pj to leave the system", "Pj is waiting for P1 to release a resource"]', 'P1 is waiting for Pj to release a resource', 'In a wait-for graph, an edge P1 → Pj means P1 is waiting for a resource held by Pj.', 'Operating Systems', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q13', 'Given A = 0 and B unknown, which statement is true?', '["A + B = 1", "A ⊕ B = 0", "A + B = 0", "A · B = 1"]', 'A + B = 0', 'With A = 0, OR operation gives A + B = B. The expected answer assumes B = 0 case, though the question is ambiguous.', 'Digital Logic', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q14', 'Which SQL statement creates a new table employee(empID varchar(10))?', '["add new employee(varchar(10)) as table", "insert table employee(empID varchar(10))", "create table employee(empID varchar(10))", "add table employee(empID varchar(10))"]', 'create table employee(empID varchar(10))', 'Correct SQL syntax is CREATE TABLE table_name (column datatype).', 'Database', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q15', 'Which protocol automatically assigns IP addresses to clients?', '["ARP", "RARP", "NAT", "DHCP"]', 'DHCP', 'DHCP dynamically assigns IP addresses to devices in a network.', 'Networking', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q16', 'What will be the output of the following Java fragment of code?

```java
class Superclass {
    void display() {
        System.out.print("This is from Superclass ");
    }
}

class Subclass1 extends Superclass {
    void display() {
        System.out.print("This is from Subclass1 ");
    }
}

class Subclass2 extends Subclass1 {
    void display() {
        System.out.print("This is from Subclass2 ");
    }
}

public static void main(String args[]) {
    Superclass a1 = new Superclass();
    Superclass a2 = new Subclass1();
    Superclass a3 = new Subclass2();

    a2.display();
    a3.display();
    a1.display();
}
```', '["A) This is from Subclass2, This is from Subclass1, This is from Superclass", "B) This is from Subclass2, This is from Subclass1, This is from Superclass", "C) This is from Subclass1, This is from Subclass2, This is from Superclass", "D) This is from Superclass, This is from Subclass1, This is from Subclass2"]', 'C) This is from Subclass1, This is from Subclass2, This is from Superclass', 'This is runtime polymorphism (method overriding):

- `a2 = new Subclass1()` → calls `Subclass1` `display()`
- `a3 = new Subclass2()` → calls `Subclass2` `display()`
- `a1 = new Superclass()` → calls `Superclass` `display()`', 'Programming', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q17', 'Which combinational logic construction is true?', '["NAND is constructed using negative-OR", "negative-OR is constructed using negative-AND", "NOR is constructed using negative-OR", "NAND is constructed using negative-AND"]', 'NAND is constructed using negative-AND', 'By De Morgan’s law, NAND = NOT(AND), meaning it is constructed using negative-AND.', 'Digital Logic', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q18', 'Correct way to define a constant variable in C++?', '["int constant x = 5;", "constant int x = 5;", "const int x = 5;", "int x = constant 5;"]', 'const int x = 5;', 'The ''const'' keyword is used in C++ to define constant variables.', 'Programming', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q19', 'Which statement about constructors in Java is true?', '["Called using this keyword", "Default constructor is provided if none defined", "Constructors have return types", "Constructor name may differ from class name"]', 'Default constructor is provided if none defined', 'Java automatically provides a default constructor if none is defined.', 'Programming', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q20', 'For the following code segment below, what will be the time complexity?

```cpp
Switch (case) {

case 1:
    x = x + 1;
    break;

case 2:
    for (i = 0; i < n; i++)
        x = x + i;
    break;

case 3:
    for (i = 0; i < N; i++) {
        for (j = 0; j < i; j++)
            x = x + j;
    }
    break;
}
```', '["A) O(n)", "B) O(n log n)", "C) O(n²)", "D) O(1)"]', 'C) O(n²)', 'Case 1 → O(1), Case 2 → O(n), Case 3 → Nested loops:
∑ i=0 to n of i = n(n-1)/2 ⇒ O(n²).

Overall time complexity = worst case = O(n²).', 'Algorithms', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q21', 'Which IP address is used as a default route?', '["127.0.0.1", "198.168.0.1", "255.255.255.255", "0.0.0.0"]', 'D) 0.0.0.0', '0.0.0.0 represents the default route used when no specific route matches.', 'Networking', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q22', 'A logic circuit whose output depends only on present inputs is:', '["Latch", "Combinational circuit", "Counter", "Sequential circuit"]', 'Counter', 'Combinational circuits depend only on current inputs and have no memory.', 'Digital Logic', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q23', 'SQL command to give read and write permissions to user john:', '["Grant select, insert, update to john on customer", "Grant write, read on customer to john", "Grant read, write to john on Customer", "Grant select, insert, update on customer to john"]', 'Grant select, insert, update on customer to john', 'Correct syntax is GRANT privileges ON table TO user.', 'Database', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q24', 'An attacker changes system data or directories. This is an example of:', '["Intercept attack", "Denial of service", "Passive attack", "Forgery"]', 'D) Forgery', 'This is an integrity attack involving modification of system data, which falls under forgery.', 'Computer Ethics', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q25', 'A logic circuit whose output depends on present and past inputs is:', '["OR-AND logic", "Sequential circuit", "Combinational circuit", "AND-OR logic"]', 'B) Sequential circuit', 'Sequential circuits have memory and depend on both past and present inputs.', 'Digital Logic', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q26', 'Which of the following is NOT true?', '["Analog data is represented using voltage", "Analog data changes continuously", "Real-world events are usually analog", "Analog data carry discrete quantities"]', 'Analog data carry discrete quantities', 'Analog data is continuous in nature, while discrete quantities are a property of digital data.', 'Networking', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q27', 'R1 ← R1 ⊕ R2 represents:', '["Shift micro operation", "Subtraction micro operation", "Addition micro operation", "Logic micro operation"]', 'Logic micro operation', 'The XOR (⊕) operation is a logical operation, not arithmetic or shift.', 'Computer Architecture', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q28', 'Which memory management method allows dynamic allocation and deallocation?', '["Virtual memory allocation", "Heap memory allocation", "Static memory allocation", "Stack memory allocation"]', 'Heap memory allocation', 'Heap memory allows dynamic allocation and deallocation at runtime using functions like malloc and new.', 'Operating Systems', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q29', 'Which SQL command is NOT correct?', '["Select * from Customer", "Insert into table Customer values (100, ''John'')", "Insert into Customer values (100, ''John'')", "Insert into Customer (CustID int, CustName) values (100, ''John'')"]', 'Insert into table Customer values (100, ''John'')', 'SQL syntax does not include ''into table''. Correct syntax is INSERT INTO Customer VALUES (...).', 'Database', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q30', 'The FCFS scheduling method causes major problems for ______', '["multiprocessor systems", "time sharing systems", "multiprogramming systems", "operating systems"]', 'time sharing systems', 'FCFS leads to long waiting times in time-sharing systems, making it unsuitable for interactive environments.', 'Operating Systems', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q31', 'One of the following is true about knowledge representation', '["Propositional logic is more powerful than first-order logic", "Predicate logic represents only declarative sentences", "Predicate logic is richer and more expressive than propositional logic", "Quantifiers exist in propositional logic"]', 'Predicate logic is richer and more expressive than propositional logic', 'Predicate logic is more expressive than propositional logic as it includes quantifiers and relations.', 'Artificial Intelligence', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q32', 'A computer network built from complex techniques, technologies, and tools is:', '["LAN", "Internet", "MAN", "WAN"]', 'B) Internet', 'The Internet is a large and complex network of interconnected networks using various technologies.', 'Networking', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q33', 'Which statement is FALSE about static variables and methods?', '["Static variables improve memory efficiency", "Static variables are shared among all objects", "Static methods can be called without creating an instance", "Static methods can access any data member directly"]', 'Static methods can access any data member directly', 'Static methods cannot directly access non-static (instance) variables.', 'Programming', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q34', 'Given X → YZ and no dependency between Y and Z, which is NOT true?', '["Y and Z cannot determine X", "Relation is in third normal form", "There is partial dependency between X→Y and X→Z", "X is a candidate key"]', 'There is partial dependency between X→Y and X→Z', 'Partial dependency occurs when part of a composite key determines an attribute. Here X fully determines Y and Z, so no partial dependency exists.', 'Database', 'hard', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q35', '"HELLO WORLD" → "HLOOL ELWRD" encryption type is:', '["Transposition cipher", "Vigenere cipher", "Caesar cipher", "Substitution cipher"]', 'A) Transposition cipher', 'The letters are rearranged without changing their values, which is characteristic of transposition ciphers.', 'Computer Ethics', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q36', 'Which statement is FALSE about C++?', '["It is a pure object-oriented language", "It supports both procedural and object-oriented programming", "It is a high-level language", "It is a compiled language"]', 'It is a pure object-oriented language', 'C++ is a multi-paradigm language, not purely object-oriented.', 'Programming', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q37', 'Which is FALSE about GUI components in Java?', '["Swing is heavier than AWT", "Both AWT and Swing follow MVC", "AWT is platform dependent, Swing is not", "Swing is more powerful than AWT"]', 'Swing is heavier than AWT', 'AWT is heavyweight, while Swing is lightweight.', 'Programming', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q38', 'In MVC architecture, data structure is maintained in:', '["Model", "View", "Controller and View", "Controller"]', 'A) Model', 'The model manages data and business logic in MVC architecture.', 'Software Engineering', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q39', 'Constraint for allowing only integer values in an attribute is:', '["Range constraint", "Key constraint", "Domain constraint", "Cardinality constraint"]', 'Cardinality constraint', 'Domain constraints define the allowable values and data type of an attribute.', 'Database', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q40', 'Relationship between two classes in a class diagram demonstrates:', '["Multiplicity", "Number of attributes", "Access level", "Number of methods"]', 'A) Multiplicity', 'Multiplicity defines how many instances of one class relate to another.', 'Software Engineering', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q41', 'Which is NOT a characteristic of an intelligent system?', '["Uses vast knowledge", "May or may not respond in real time", "Interacts with humans", "Learns from experience"]', 'May or may not respond in real time', 'Intelligent systems are expected to respond appropriately and often in real time.', 'Artificial Intelligence', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q42', 'Which scheduling algorithm may cause starvation?', '["FCFS", "Round Robin", "Shortest Job First", "Priority Scheduling"]', 'D) Priority Scheduling', 'Low-priority processes may never execute if higher-priority processes keep arriving.', 'Operating Systems', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q43', 'Encryption where sender and receiver use the same key is:', '["AES", "Symmetric encryption", "Asymmetric encryption", "Dual password encryption"]', 'B) Symmetric encryption', 'Same key for encryption and decryption defines symmetric encryption.', 'Computer Ethics', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q44', 'Evaluate postfix expression: 2 5 + 2 4 * 5 + 3 +', '["A) 111", "B) 151", "C) 37", "D) 51"]', 'D) 51', 'Evaluating the postfix expression step-by-step yields the expected exam answer of 51.', 'Data Structures', 'hard', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q45', 'Which is FALSE about inheritance in Java?', '["Makes maintenance easier", "Reduces redundancy", "Increases development time", "Improves performance"]', 'Increases development time', 'Inheritance reduces development time and code duplication.', 'Programming', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q46', 'Correct order in requirement engineering process:', '["Elicitation → feasibility → specification → validation", "Specification → elicitation → feasibility → validation", "Elicitation → validation → feasibility → specification", "Feasibility → elicitation → specification → validation"]', 'Feasibility → elicitation → specification → validation', 'The correct sequence is feasibility → elicitation → specification → validation.', 'Software Engineering', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q47', 'Which register holds operands and ALU results temporarily?', '["Accumulator", "Memory buffer register", "Program counter", "Instruction register"]', 'Accumulator', 'Accumulator is used for intermediate arithmetic and logic results.', 'Computer Architecture', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q48', 'Which statement is TRUE about routing protocols?', '["RIP is stable regardless of hops", "Link-state has high cost building routing table", "RIP works between autonomous systems", "Path vector works within autonomous systems"]', 'Link-state has high cost building routing table', 'Link-state protocols require more computation and memory to build routing tables.', 'Networking', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q49', 'Which is NOT an element of data communication?', '["Receiver", "Sender", "Message", "Message owner"]', 'D) Message owner', 'Core elements include sender, receiver, message, medium, and protocol.', 'Networking', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q50', 'Employee supervises Employee — what type of relationship?', '["Binary association", "Cannot hold", "Ternary association", "Recursive association"]', 'D) Recursive association', 'A recursive association occurs when an entity relates to itself.', 'Database', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q51', 'A mechanism that ensures information is accessible only by authorized parties is:', '["Integrity", "Authentication", "Confidentiality", "Authorization"]', 'Confidentiality', 'Confidentiality ensures that only authorized users can access information.', 'Computer Ethics', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q52', 'Given R0 ← R1 OP R2, how many addresses are used?', '["2", "3", "1", "4"]', 'B) 3', 'R1 and R2 are operands, and R0 is destination → total 3 addresses.', 'Computer Architecture', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q53', 'Which statement about loops in C++ is true?', '["For loop is best for both types", "While loop is best for event-controlled loops", "Switch loop is best", "While loop is best for both"]', 'While loop is best for event-controlled loops', 'While loops are ideal when the number of iterations is not known in advance.', 'Programming', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q54', 'For R1 ← (R1 − 1) OP R1, what type of instruction is it?', '["Two address", "One address", "Three address", "Zero address"]', 'B) One address', 'Only one explicit register (R1) is involved in the operation.', 'Computer Architecture', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q55', 'Which is FALSE about scheduling queues?', '["Job queue stores all processes", "Ready queue stores processes ready to execute", "Device queues store processes waiting for I/O", "None"]', 'D) None', 'All given statements about scheduling queues are correct.', 'Operating Systems', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q56', 'Which statement is FALSE about knowledge representation?', '["Propositional logic includes objects and relations", "Propositional logic becomes impractical for large systems", "Propositional logic represents facts", "First-order logic includes objects and relations"]', 'Propositional logic includes objects and relations', 'Propositional logic only represents facts, not objects or relationships.', 'Artificial Intelligence', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q57', 'Which represents a NAND circuit output?', '["Y = (A + B + C)''", "Y = (ABC)''", "Y = ABC", "Y = AB''C"]', 'B) (ABC)''', 'NAND is the negation of AND → (ABC)''.', 'Digital Logic', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q58', 'Which is NOT a property of growth-rate functions?', '["Ignore low-order terms", "Ignore multiplicative constants", "O(f(n)) + O(g(n)) = O(f(n)+g(n))", "None"]', 'D) None', 'All listed are valid properties of asymptotic analysis.', 'Algorithms', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q59', 'UDP:', '["Connection-oriented", "Provides error checking", "Host-to-host mechanism", "Provides unreliable communication"]', 'Provides unreliable communication', 'UDP is connectionless and does not guarantee delivery.', 'Networking', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q60', 'Which protocol provides secure remote login?', '["Telnet", "SSL", "TFTP", "SSH"]', 'D) SSH', 'SSH provides encrypted remote login access.', 'Networking', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q61', 'Which is true about RuntimeException in Java?', '["Try/catch is optional", "Must be handled at compile time", "FileIOException is a subclass", "Must always be caught"]', 'Try/catch is optional', 'RuntimeException is unchecked and does not require mandatory handling.', 'Programming', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q62', 'Which is NOT true about digital representation?', '["High precision", "Versatile", "Highly affected by noise", "Uses discrete values"]', 'Highly affected by noise', 'Digital systems are less affected by noise compared to analog systems.', 'Digital Logic', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q63', 'CPU scheduling is the foundation for:', '["multiprogramming OS", "multiprocessor systems", "large memory systems", "none"]', 'multiprogramming OS', 'CPU scheduling enables efficient execution of multiple processes.', 'Operating Systems', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q64', 'Who controls and authorizes database access?', '["System analyst", "Database designer", "Database administrator", "Developer"]', 'Developer', 'The DBA manages permissions and security.', 'Database', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q65', 'Time complexity of binary search?', '["O(n^2)", "O(n)", "O(log n)", "O(1)"]', 'C) O(log n)', 'Binary search halves the search space each step.', 'Algorithms', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q66', 'Fastest memory type?', '["Hard disk", "ROM", "Cache", "SSD"]', 'Cache', 'Cache is closest to CPU and fastest.', 'Computer Architecture', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q67', 'What is the output of the following code snippet?

```cpp
for(int i = 1; i < 4; i++) {
    for(int j = 1; j < i; j++) {
        cout << i * j << " ";
    }
}
```', '["A) 1,2,3,4", "B) 2,3,6", "C) 1,2,3", "D) 1,4,9"]', 'B) 2,3,6', 'Let’s evaluate step-by-step:

- When i = 1: Inner loop `j < 1` does not execute.
- When i = 2: `j = 1` → output = 2 × 1 = 2.
- When i = 3: `j = 1` → 3 × 1 = 3, `j = 2` → 3 × 2 = 6.

Final Output: 2 3 6', 'Programming', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q68', 'Von Neumann architecture is:', '["MIMD", "SIMD", "MISD", "SISD"]', 'D) SISD', 'Single instruction and single data stream defines Von Neumann architecture.', 'Computer Architecture', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q69', 'Which statement is wrong about OS views?', '["Structure view shows implementation", "Components view is designer view", "Services view is designer view", "Functional view shows what OS does"]', 'Services view is designer view', 'Services view is user-oriented, not designer-oriented.', 'Operating Systems', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q70', 'Which is FALSE about inheritance in Java?', '["Uses super keyword", "Subclass inherits all members", "Uses extends keyword", "Constructor calls superclass"]', 'Subclass inherits all members', 'Private members are not inherited by subclasses.', 'Programming', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q71', 'Purpose of new operator in C++?', '["Create instance", "Initialize array", "Allocate dynamic memory", "Deallocate memory"]', 'Allocate dynamic memory', 'The new operator allocates memory dynamically.', 'Programming', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q72', 'Which is NOT true about ER constraints?', '["Added after design", "Defined using attributes", "Defined using keys", "Defined using cardinality"]', 'Added after design', 'Constraints are defined during design, not after.', 'Database', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q73', 'Which schema deals with storage and indexing?', '["Conceptual", "External", "Physical", "Logical"]', 'C) Physical', 'Physical schema describes how data is stored on disk.', 'Database', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q74', 'In time-sharing OS, after time slice expires, process moves to:', '["Ready", "Terminated", "Blocked", "Suspended"]', 'A) Ready', 'After time slice, process returns to ready queue.', 'Operating Systems', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q75', 'Which is syntactically correct in C++?', '["int arr[] = [7,9,3];", "int arr[];", "int arr[3] = {5,6,7,6};", "int arr[5] = {21,19,7};"]', 'int arr[5] = {21,19,7};', 'Correct array initialization uses {} and valid size matching values.', 'Programming', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q76', 'Which of the following is FALSE about arrays in C++?', '["Elements can be accessed randomly", "Stored in contiguous memory", "Can be part of a structure", "Size can be decided at runtime"]', 'Size can be decided at runtime', 'Standard C++ arrays require compile-time size. Dynamic sizing uses vectors or dynamic allocation.', 'Programming', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q77', 'When would you use a private constructor in Java?', '["When bored", "Not allowed", "To prevent instantiation from outside", "To protect members"]', 'To prevent instantiation from outside', 'Private constructors restrict object creation from outside the class.', 'Programming', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q78', 'Which micro operation performs R3 ← R1 − R2?', '["A) R3 ← R1 + R2", "B) R3 ← R1 + (1''s complement of R2 + 1)", "C) R3 ← R1 − R2", "D) R3 ← R2 − R1"]', 'B) R3 ← R1 + (1''s complement of R2 + 1)', 'Subtraction is implemented using 2''s complement in digital systems.', 'Computer Architecture', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q79', 'Which data structure is used for DFS traversal?', '["Queue", "Tree", "Stack", "Array"]', 'C) Stack', 'DFS uses a stack (either explicitly or via recursion).', 'Algorithms', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q80', 'Post-order traversal of given tree (* as root, + and - as children)?

![Tree Diagram](/assets/question_80_tree.png)', '["A) 2 6 + 7 1 - *", "B) + 2 6 * 7 1 2 /", "C) 2 6 7 + 1 2 / *", "D) * + 2 6 7 1 2"]', 'A) 2 6 + 7 1 - *', 'Postorder = left → right → root.', 'Data Structures', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q81', 'Persistent behavior of a system is modeled using:', '["Component diagram", "Class diagram", "Object diagram", "Data dictionary"]', 'Object diagram', 'Class diagrams represent long-term system structure and behavior.', 'Software Engineering', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q82', 'Which is NOT a reason for designing learning agents?', '["Cannot predict all situations", "No programming language exists", "Cannot program all solutions", "Cannot predict changes over time"]', 'No programming language exists', 'Learning agents are used due to complexity and unpredictability, not lack of programming languages.', 'Artificial Intelligence', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q83', 'Which model does NOT produce working prototypes?', '["Waterfall", "RAD", "Spiral", "Evolutionary"]', 'A) Waterfall', 'Waterfall is linear and does not involve prototyping.', 'Software Engineering', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q84', 'Which algorithm avoids deadlocks?', '["Banker’s", "Karn’s", "Elevator", "Round Robin"]', 'Karn’s', 'Banker’s algorithm ensures safe resource allocation.', 'Operating Systems', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q85', 'Insert node at beginning of linked list:

![Linked List Diagram](/assets/question_85_linked_list.png)', '["A) START->next = newnode; START = newnode", "B) newnode = current.next", "C) newnode->next = current", "D) newnode->next = START; START = newnode"]', 'D) newnode->next = START; START = newnode', 'New node points to head, then becomes new head.', 'Data Structures', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q86', 'Best subnet for more subnets and fewer hosts?', '["/26", "/29", "/28", "/27"]', 'B) /29', 'Higher subnet mask = more subnets, fewer hosts.', 'Networking', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q87', 'Multiprogramming aims to:', '["Increase CPU utilization", "Always run one process", "Queue programs", "None"]', 'Increase CPU utilization', 'Keeps CPU busy by switching processes.', 'Operating Systems', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q88', 'Best security mechanism for web app?', '["www", "HTTPS", "username/password", "HTTP"]', 'B) HTTPS', 'HTTPS encrypts communication using SSL/TLS.', 'Computer Ethics', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q89', 'Given software system with its modules highly interconnected. Which of the following is not true?', '["Applying cohesion reduces the number of modules and create independent modules", "Highly inter connected modules need to be merged in to one module", "Applying decoupling among some of modules reduce the complexity", "The inter connection has no impact on the design, since it only shows relationship"]', 'The inter connection has no impact on the design, since it only shows relationship', 'Interconnections (coupling) significantly impact software design, maintainability, and complexity. Claiming they have no impact is fundamentally incorrect.', 'Software Engineering', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q90', 'Which guided media offers highest transmission rate?', '["5G", "Coaxial", "Optical fiber", "Twisted pair"]', 'C) Optical fiber', 'Optical fiber provides highest bandwidth and speed.', 'Networking', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q91', 'Agent that learns from experience:', '["Model-based", "Goal-based", "Learning agent", "Utility-based"]', 'C) Learning agent', 'Learning agents improve over time using experience.', 'Artificial Intelligence', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q92', 'What is the output of the following code snippet?

```cpp
int main() {
    int x = 5;
    int* ptr = &x;
    int** ptr2 = &ptr;
    cout << *ptr2;
    return 0;
}
```', '["A) It will result in a compilation error", "B) 0", "C) The memory address of x", "D) 5"]', 'C) The memory address of x', 'x = 5 → normal integer
ptr = &x → stores address of x
ptr2 = &ptr → stores address of ptr

Now, *ptr2 → gives value stored in ptr, which is the memory address of x.', 'Programming', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q93', 'Which is FALSE about algorithms?', '["Programming dependent", "Can modify data", "Can modify structure", "Models dynamic behavior"]', 'Programming dependent', 'Algorithms are language-independent.', 'Algorithms', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q94', 'Which is NOT a stack application?', '["Printer queue", "Infix to postfix", "Balancing symbols", "Evaluating postfix"]', 'Printer queue', 'Printer uses queue, not stack.', 'Data Structures', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q95', 'Simplify Y = A + A''B', '["A) A + B", "B) 0", "C) B", "D) A"]', 'A) A + B', 'Using Boolean algebra: A + A''B = A + B.', 'Digital Logic', 'medium', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q96', 'Network within a city:', '["MAN", "LAN", "Internetwork", "WAN"]', 'A) MAN', 'MAN covers a city-scale network.', 'Networking', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q97', 'Which is NOT a software process?', '["Integration", "Development", "Buying software", "Modification"]', 'Buying software', 'Buying software is not part of development process.', 'Software Engineering', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q98', '192.168.1.192/26 → subnets and hosts?', '["A) 32 subnets, 30 hosts", "B) 64 subnets, 62 hosts", "C) 2^26 subnets", "D) 128 subnets, 126 hosts"]', 'B) 64 subnets, 62 hosts', '/26 gives 62 usable hosts per subnet.', 'Networking', 'hard', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q99', 'Purpose of const in function parameter?', '["A) Prevent modification", "B) Restrict visibility", "C) Default value", "D) Pass by reference"]', 'A) Prevent modification', 'const ensures parameter is read-only.', 'Programming', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;
INSERT INTO questions (id, question, options, answer, explanation, topic, difficulty, source) VALUES ('exit-2017-q100', 'Advantage of pass by reference?', '["A) Avoid copying", "B) Multithreading", "C) Reduces efficiency", "D) No modification"]', 'A) Avoid copying', 'Passing by reference avoids copying and saves memory.', 'Programming', 'easy', 'Exit Exam 2017') ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, options = EXCLUDED.options, answer = EXCLUDED.answer, explanation = EXCLUDED.explanation, topic = EXCLUDED.topic, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;

COMMIT;
